### ISSUE TITLE
The trick to trim text lines in bashbar.sh doesn't work with columns

### ISSUE THREAD

**Issue by silviuvulcan** [metal3d/bashsimplecurses#13]
Hi,

I'm building a status script where I'd like lines of text displayed using the same way the latest kernel messages are printed in bashbar.sh but in a column. For some reason text spills below the left windows.

Below is my modified bashbar.sh (basically added 50% to all windows)

``` bash
#!/bin/bash

. `dirname $0`/simple_curses.sh

main (){
    #basic informations, hostname, date,...
    window "`hostname`" "red" "50%"
    append "`date`"
    addsep
    append_tabbed "Up since|`uptime | cut -f1 -d"," | sed 's/^ *//' | cut -f3- -d" "`" 2 "|"
    append_tabbed "Users:`uptime | cut -f2 -d"," | sed 's/^ *//'| cut -f1 -d" "`" 2
    append_tabbed "`awk '{print "Load average:" $1 " " $2 " " $3}' < /proc/loadavg`" 2
    endwin

    #memory usage
    window "Memory usage" "red" "50%"
    append_tabbed `cat /proc/meminfo | awk '/MemTotal/ {print "Total:" $2/1024}'` 2
    append_tabbed `cat /proc/meminfo | awk '/MemFree/ {print "Used:" $2/1024}'` 2
    endwin

        col_right
        move_up

    #5 more used process ordered by cpu and memory usage
    window "Processus taking memory and CPU" "green" "50%"
    for i in `seq 2 6`; do
        append_tabbed "`ps ax -o pid,rss,pcpu,ucmd --sort=-cpu,-rss | sed -n "$i,$i p" | awk '{printf "%s: %smo:  %s%%" , $4, $2/1024, $3 }'`" 3
    done
    endwin

    #get dmesg, log it then send to deskbar
    window "Last kernel messages" "blue" "50%"
    dmesg | tail -n 10 > /dev/shm/deskbar.dmesg
    append_file /dev/shm/deskbar.dmesg
    rm -f /dev/shm/deskbar.dmesg
    endwin

    #a special manipulation to get net interfaces  and IP
    window "Inet interfaces" "grey" "50%"
    _ifaces=$(for inet in `ifconfig | cut -f1 -d " " | sed -n "/./ p"`; do ifconfig $inet | awk 'BEGIN{printf "%s", "'"$inet"'"} /adr:/ {printf ":%s\n", $2}'|sed 's/adr://'; done)
    for ifac in $_ifaces; do
        append_tabbed  "$ifac" 2
    done
    endwin
}
main_loop 0.5
```

![screenshot](https://cloud.githubusercontent.com/assets/2470335/10558614/29f5cc38-74df-11e5-9229-349b6e97146f.png)

Am I doing something wrong?

Cheers and thanks!

**Comment by metal3d** [comment]
I'll take a look tonight :)

**Comment by metal3d** [comment]
You were right. I'll make a review and push you example. I'll put your nickname in contributors.
Thanks a lot

**Comment by Savasci** [comment]
Hm, is this fixed? I think I have the exact same issue. Could you comment on that please? Thanks for your great work, metal3d!

**Comment by metal3d** [comment]
Ok I didn't understand right the issue.
I've got the issue, I have to check how to truncate lines.
Currently checking solutions, sorry for the late answers, I'm very busy by job :)

**Comment by metal3d** [comment]
Can you please test the last simple_curses.sh script (master branch) to check if your problem persists ?

**Comment by Savasci** [comment]
Thanks for checking, metal3d! I tested with the code above from silviuvulcan, it no longer spills over. I'll retry with what I had in mind but I think this one is fixed.

**Comment by metal3d** [comment]
I've some validation to do, but that was not so complicated to change.
Thanks for that issue.

**Comment by metal3d** [comment]
If this is fixed, can you tell me to let me close that issue.

Note: I now have more time to work on my projects, so I will continue developpement

**Comment by metal3d** [comment]
Without any other comment, I close that issue. If the problem persists, please inform me.

Thanks

**Comment by Savasci** [comment]
Thanks, metal3d! I just checked with my version and the current trunk works fine. Thank you for your contribution!
