### ISSUE TITLE
UTF-8 regex

### ISSUE THREAD

**Issue by marshalm** [metal3d/bashsimplecurses#15]
Hi,

Firstly, thank you for creating this package, it works like a dream.   I have detected a small issue when the simple_curses.sh script tries to determine if UTF-8 is set.  The issue maybe related to the version of bash.  My LANG is set to en_GB.UTF-8.

$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)

To solve this issue I had to remove the " " marks around the regex on line 91:
```
 -    if [[ -z "$ASCIIMODE" && $LANG =~ ".*\.UTF-8" ]] ; then ASCIIMODE=utf8; fi
 +    if [[ -z "$ASCIIMODE" && $LANG =~ .*\.UTF-8 ]] ; then ASCIIMODE=utf8; fi
```

Hopes this helps someone !

Many thanks
Martin

**Comment by metal3d** [comment]
And you're right. I'll fix it today un a few hours. Thanks a lot !

**Comment by metal3d** [comment]
You may test :)

**Comment by marshalm** [comment]
perfect - thank you :-)

**Comment by metal3d** [comment]
Thanks to you ! :)
