### ISSUE TITLE
echo -e in Makefile

### ISSUE THREAD

**Issue by properlyindented** [metal3d/bashsimplecurses#21]
When running
  make test
it comes out really bad looking on Debian 8:

-e Warning - You should install caca-utils or img2txt command

strace(1) shows that /bin/sh is used.
man sh gives the manual page for dash, and that manual page shows that the builtin echo does not support -e as an option.
Setting SHELL=bash as the first line in Makefile makes the output look at expected on Debian 8.

I'm not sure if some creates other problems or if some systems require a full pathname to bash.

**Comment by metal3d** [comment]
That's right, "make" is using sh by default and I should change the Makefile to avoid that problem. I will make a change soon.

Sorry for late answer, at this time (this 2 years) I'm very busy. I will do it very soon
