### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by skamsie** [metal3d/bashsimplecurses#26]
I tried running some of the examples, but instead of colors I get ansi escape codes... Any hints how to make it work? I tried with both the terminal app and iterm on macOS.

![screen shot 2018-01-17 at 10 34 22 am](https://user-images.githubusercontent.com/7014744/35035687-7eeda820-fb72-11e7-81b4-e298b1bfceab.png)

**Comment by vaidd4** [comment]
Your terminal (or shell) doesn't seems to handdle the `\E[` escape characters.
You can try editing the `simple_curses.sh` file and replacing the escape characters by `\033[` (arround line 200 to 260):

Try replacing all the:
```
echo -ne "\E[..."
```
By 
```
echo -ne "\033[..."
```

**Comment by metal3d** [comment]
I think @vaidd4 is right, if that's true, I will change escape char in a futur release... Or maybe I should do that right now... I will try today.

**Comment by skamsie** [comment]
@vaidd4, @metal3d yes that would solve it. thanks for looking into this.
