### ISSUE TITLE
Make better documentation

### ISSUE THREAD

**Issue by metal3d** [metal3d/bashsimplecurses#43]
The documentation is really poor and full of English mistakes.

**Comment by jtbx** [comment]
@metal3d I've made a PR to fix all of your mistakes :grinning: #55.
Keep in mind there's 3 image links I've found that just lead to 404s, so try to re-upload those images and replace the warnings I put there with working image links.

**Comment by metal3d** [comment]
Thanks a lot. For the images, maybe it's better to leave them as 404 then I'll redo them in another commit. Can you only revert this ?
PS: I'm sorry if I take a long time to answer. A lot of work + a baby who will enter this world in a few days...

**Comment by jtbx** [comment]
Okay, I'll remove them :)
