### ISSUE TITLE
The first line of  windows always jumps when refreshing

### ISSUE THREAD

**Issue by Cheemer** [metal3d/bashsimplecurses#47]
![ezgif-2-dcafe3824de4](https://user-images.githubusercontent.com/5573870/94377122-980e8800-0151-11eb-8f7a-cad06ba631bb.gif)

I have tried some emulation terminals such as xshell and putty with same result.

I used the last version of bashsimplecurses.

test.sh

#!/bin/bash

#import library, please check path
#source /usr/lib/simple_curses.sh
source simple_curses.sh

#Then, you must create a "main" function:
main () {
    #your code here, you can add some windows, text...
    window "title" "red" "50%"
    append "Text..."
    endwin
}

#then, you can execute loop:
main_loop 1

**Comment by rlegene** [comment]
This is caused by endwin which correctly goes to the bottom of the screen and starts the cursor on a new line by itself.
I think the error isn't in bashsimplecurses but rather in the example.

**Comment by Cheemer** [comment]
thanks for your reply, i already solved the problem,because in function refresh,echo "" > $BSC_BUFFER will made a return in $BSC_BUFFER, use > $BSC_BUFFER  can empty the file to 0
