### ISSUE TITLE
Take a look at my fork. (POSIX Shell fork)

### ISSUE THREAD

**Issue by Nomagno** [metal3d/bashsimplecurses#49]
I've made a fully POSIX Shell compliant fork [you can take a look at here](https://gitea.com/Nomagno/ShellCurses). While I have no intention of opening a pull request, I do have some interesting features like better ASCII detection, and a bit of a hack that replaces the sleep with a blocking `read` timeout, but ends up being a very elegant solution to sneak fully functioning user input into the current codebase. Feel free to take a look.

**Comment by metal3d** [comment]
It's a pitty that you don't want to make a PR :)
