### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [metal3d/bashsimplecurses#6]
```
Hi,

Can you create a progress bar ( to copy a file or monitoring memory for
example ) ?

Best regard
David aka hvad

```

Original issue reported on code.google.com by `david.ha...@gmail.com` on 12 Jun 2009 at 8:01

**Comment by metal3d** [comment]
There is now a progress bar, please try it and leave a comment if it doesn't work. Thanks !
