### ISSUE TITLE
How can I get user input in a window?

### ISSUE THREAD

**Issue by shebangcode** [metal3d/bashsimplecurses#61]
Hello, I'm trying to create a TUI for my app, yeast. But for this, I need to get user input in the window. Can someone provide me with some help?

Thanks in advance,
shebangcode

**Comment by metal3d** [comment]
Hi,

BSC is not intended to create interactive interface. You can override `update()` function in your script (see examples) and try to use the `read` function (with `-n1` option for example, that will directly send the pressed key)

Note that we are trying to implement "events". See #33 issue
